<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-4T13P6B" failures="0" tests="2" name="com.vtiger.organizationTest.CreateOrganizationWithIndustyAndTypeTest" time="16.462" errors="1" timestamp="2022-05-23T06:13:31 IST" skipped="0">
  <testcase classname="com.vtiger.organizationTest.CreateOrganizationWithIndustyAndTypeTest" name="createOrganizationWithIndustyAndTypeTest" time="16.461"/>
  <system-out/>
  <testcase classname="com.vtiger.organizationTest.CreateOrganizationWithIndustyAndTypeTest" name="afterSuiteTest" time="0.001">
    <error message="Cannot invoke &quot;org.apache.poi.ss.usermodel.Workbook.close()&quot; because &quot;this.wb&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Workbook.close()" because "this.wb" is null
at com.sdet34l1.genericLibrary.ExcelLibrary.closeExcel(ExcelLibrary.java:105)
at com.sdet34l1.genericLibrary.BaseClass.afterSuiteTest(BaseClass.java:147)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:344)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- afterSuiteTest -->
  <system-out/>
</testsuite> <!-- com.vtiger.organizationTest.CreateOrganizationWithIndustyAndTypeTest -->
